export enum SQLKeyword {
    ON = 'ON',
    SET = 'SET',
    SPACE = ' ',
    ASSIGN = '=',
    FROM = 'FROM',
    JOIN = 'JOIN',
    LEFT = 'LEFT',
    INNER = 'INNER',
    LIMIT = 'LIMIT',
    WHERE = 'WHERE',
    DELETE = 'DELETE',
    EXISTS = 'EXISTS',
    OFFSET = 'OFFSET',
    SELECT = 'SELECT',
    VALUES = 'VALUES',
    UPDATE = 'UPDATE',
    OPEN_FUNCTION = '(',
    CLOSE_FUNCTION = ')',
    PROJECTION_ALL = '*',
    TYPE_SEPARATOR = '::',
    FIELD_SEPARATOR = ',',
    RETURNING = 'RETURNING',
    OPEN_PLACEHOLDER = '${',
    CLOSE_PLACEHOLDER = '}',
    TABLE_FIELD_SEPARATOR = '.',
    INSERT_PREAMBLE = 'INSERT INTO'
};